<?php

// node rnaseq
require_once 'includes/tripal_rnaseq_exp_loader.inc';
require_once 'includes/tripal_rnaseq.chado_node.inc';

// theme preprocessing
require_once "theme/tripal_rnaseq.theme.inc";

/**
 * Implements hook_menu().
 */
function tripal_rnaseq_menu() {
  $items = array();
  
  // === main admin page ===
  $items['admin/tripal/extension/tripal_rnaseq'] = array(
    'title' => 'Tripal RNASeq',
    'description' => 'A module for RNASeq.',
    'access arguments' => array('administer'),
  );

  // RNA-seq loading/update.
  /**
  $items['admin/tripal/extension/tripal_rnaseq/load'] = array(
    'title' => 'Load',
    'description' => 'Load RNASeq expression.',
    'access arguments' => array('administer'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('tripal_rnaseq_load'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 5,
  );
  */

  // === help === 
  $items['admin/tripal/extension/tripal_rnaseq/help'] = array(
    'title' => 'Help',
    'description' => 'Document for how to use Tripal RNASeq.',
    'access arguments' => array('administer'),
    'page callback' => 'theme',
    'page arguments' => array('tripal_rnaseq_help'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 10,
  );

  // === home ===
  $items['rnaseq/home'] = array(
    'title' => 'RNASeq Expression',
    'access arguments' => array('access content'),
    'page callback' => 'theme',
    'page arguments' => array('tripal_rnaseq_home'),
    'type' => MENU_NORMAL_ITEM,
    'weight' => 10,
  );

  return $items; 
}

/**
 * Implements hook_theme().
 */
function tripal_rnaseq_theme() {
  $items = array();
  $path = drupal_get_path('module', 'tripal_rnaseq');

  $items['tripal_rnaseq_home'] = array(
    'template' => 'tripal_rnaseq_home',
    'path' => "$path/theme",
  );

  $items['tripal_rnaseq_help'] = array(
    'template' => 'tripal_rnaseq_help',
    'path' => "$path/theme",
  );

  $items['tripal_feature_rnaseq_expression'] = array(
    'template' => 'tripal_feature_rnaseq_expression',
    'path' => "$path/theme",
  );

  return $items;
}

function tripal_rnaseq_help($path, $arg) {
  if ($path == 'admin/help#tripal_rnaseq') {
    return theme('tripal_rnaseq_help');
  }  
}


