<?php

// api
require_once 'api/tripal_rnaseq.api.inc';

// node rnaseq
require_once 'includes/tripal_rnaseq_exp_loader.inc';
require_once 'includes/tripal_rnaseq.chado_node.inc';

// tools
require_once 'includes/tripal_rnaseq_analysis.inc';


// theme preprocessing
require_once "theme/tripal_rnaseq.theme.inc";

/**
 * Implements hook_menu().
 */
function tripal_rnaseq_menu() {
  $items = array();
  
  // === main admin page ===
  $items['admin/tripal/extension/tripal_rnaseq'] = array(
    'title' => 'Tripal RNASeq',
    'description' => 'A module for RNASeq.',
    'access arguments' => array('administer'),
  );

  // === help === 
  $items['admin/tripal/extension/tripal_rnaseq/help'] = array(
    'title' => 'Help',
    'description' => 'Document for how to use Tripal RNASeq.',
    'access arguments' => array('administer'),
    'page callback' => 'theme',
    'page arguments' => array('tripal_rnaseq_help'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 10,
  );

  // === home ===
  $items['rnaseq/home'] = array(
    'title' => 'Cucurbit Expression Atlas',
    'access arguments' => array('access content'),
    'page callback' => 'theme',
    'page arguments' => array('tripal_rnaseq_home'),
    'type' => MENU_NORMAL_ITEM,
    'weight' => 10,
  );

  // === project ===
  $items['rnaseq/%/%'] = array(
    'title' => 'Cucurbit Expression Atlas',
    'access arguments' => array('access content'),
    'page callback' => 'tripal_rnaseq_exp',
    'page arguments' => array(1, 2),
    'type' => MENU_NORMAL_ITEM,
    'weight' => 10,
  );

  // === analysis === 
  $items['rnaseq/analysis'] = array(
    'title' => 'RNASeq analysis',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('tripal_rnaseq_analysis_form'),
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM,
  );

  $items['rnaseq/analysisresult'] = array(
    'title' => 'RNASeq analysis',
    'page callback' => 'tripal_rnaseq_analysis_result',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Implements hook_theme().
 */
function tripal_rnaseq_theme() {
  $items = array();
  $path = drupal_get_path('module', 'tripal_rnaseq');

  $items['tripal_rnaseq_home'] = array(
    'template' => 'tripal_rnaseq_home',
    'path' => "$path/theme",
  );

  $items['tripal_rnaseq_help'] = array(
    'template' => 'tripal_rnaseq_help',
    'path' => "$path/theme",
  );

  // show project and sample information
  $items['tripal_rnaseq_exp'] = array(
    'template' => 'tripal_rnaseq_exp',
    'path' => "$path/theme",
  );

  // show histrogram 
  $items['tripal_feature_rnaseq_expression'] = array(
    'template' => 'tripal_feature_rnaseq_expression',
    'path' => "$path/theme",
  );

  // show heatmap of analysis result
  $items['tripal_rnaseq_analysis'] = array(
    'template' => 'tripal_rnaseq_analysis',
    'path' => "$path/theme",
  );

  return $items;
}

function tripal_rnaseq_help($path, $arg) {
  if ($path == 'admin/help#tripal_rnaseq') {
    return theme('tripal_rnaseq_help');
  }  
}

function tripal_rnaseq_exp($org, $project_id) { 
  // save select project and general organism to session
  $_SESSION['tripal_rnaseq_analysis']['general_org'] = $org;
  $_SESSION['tripal_rnaseq_analysis']['project_id']  = $project_id; 
  return theme('tripal_rnaseq_exp', array('general_org' => $org, 'project_id'=>$project_id));
}

